apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:solexmb/bookstore.git
    targetRevision: HEAD
    path: k8s/develop
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true