apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:solexmb/bookstore.git
    targetRevision: demo-01
    path: k8s/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true